dwords_hand = set([u'deface', u'consider', u'vile', u'impression', u'particular', u'foul',
u'four', u'unrest', u'sleep', u'follow', u'appetite', u'captain', u'hate',
u'whose', u'careful', u"lov'd", u'father', u'young', u'spirit', u'to',
u'charge', u'painter', u'under', u"is't", u'lord', u'sorry', u'pleasing',
u'worth', u'shoot', u'lack', u'advantage', u'song', u'far', u'dispense',
u'rhyme', u"confess'd", u'votary', u'worst', u'jack', u'frailty', u'trouble',
u'feeble', u'vouchsafe', u'heaven', u'prize', u'hath', u'tear', u'die',
u"miss'd", u'fearful', u'race', u'plain', u'small', u"'gainst", u"i'll",
u'prevent', u'says', u'minion', u'sigh', u'sign', u'invention', u'plead',
u"show'st", u'idolatry', u'quill', u'drinks', u'conscience', u'will', u'what',
u'curse', u'hide', u'appear', u"ne'er", u'clock', u'waning', u'thunder',
u'assistance', u'foison', u'above', u'nurse', u'ever', u'doting', u'wilt',
u'wail', u'clerk', u'men', u'water', u"sweet'st", u'let', u'active', u'sing',
u"toil'd", u'darkly', u'extreme', u'dry', u'boy', u'great', u'stormy',
u'enmity', u'guilty', u'bow', u'sword', u'defeat', u'action',
u'therein', u'proof', u'honor', u'golden', u'love', u'perfume', u'sire',
u'compare', u'bloody', u'brought', u'put', u'wit', u'stern', u'limb',
u'fiend', u'glance', u'should', u"pow'r", u'teach', u'cloud', u'desiring',
u"lovers'", u"o'erworn", u'fee', u'eye', u'proceed', u'would', u'aye',
u'reproach', u'faint', u"poison'd", u'wood', u'prey', u'therefore', u'strike',
u'bliss', u'doom', u'tell', u'loving', u'wretched', u'babe', u'knows',
u'holy', u'wary', u'afford', u"ow'st", u"conquer'd", u'hurt', u'grief',
u'excuse', u'warm', u'virtue', u'excellent', u'known', u'hold', u'harvest',
u'suffered', u'glad', u'must', u'fly', u'lust', u'word', u'room', u'err',
u'middle', u'ride', u'work', u'soul', u"dress'd", u'remain', u'sour', u'nine',
u'sharp', u'of', u'meet', u'root', u'breeds', u'beautiful', u'dedicated',
u'visage', u'saith', u'sense', u"prick'd", u'honey', u'heard', u'woman',
u'something', u'want', u'phrase', u'offense', u'dress', u'ceremony', u'huge',
u'early', u'compounded', u'seest', u'needy', u'travel', u'comfort', u'very',
u'hot', u'forest', u'pure', u'familiar', u'answer', u'chase', u'sworn',
u'creature', u'lamb', u'mar', u'description', u'beauty', u'less', u'after',
u'wrong', u'mad', u'date', u'dove', u'parallel', u'man', u'light',
u'shady', u'jealious', u"stain'd", u'purging', u'wink', u'shore', u'writ',
u'deceive', u'alack', u'dream', u'wouldst', u'turns', u'minded', u'serving',
u'help', u'indeed', u'over', u'soon', u"y'", u'brain', u'beguile',
u"conceal'd", u'through', u'tyrant', u'shake', u'suffer', u'worship',
u'before', u'trifle', u'steel', u'pent', u'fit', u'thence', u'nymph', u'maid',
u'threescore', u'choose', u'nobler', u'bereft', u'forbear', u'then', 
u'good', u'sacred', u'motley', u'enrich', u'break', u'esteemed',
u'thereof', u'party', u'not', u'one', u'silver', u'nor', u'rhetoric',
u'name', u'servant', u'feast', u'victory', u'truth', u'each', u'found',
u'presenteth', u'gazing', u'mean', u'heavy', u"charg'd", u'dissuade',
u"confin'd", u"call'd", u'doing', u'garment', u'waking', u'our', u'naming',
u'beyond', u'tenth', u"remov'd", u'special', u'borne', u'decree', u'flower',
u'attend', u'space', u"deserv'd", u'god', u'confess', u'since', u'looking',
u'fountain', u'medicine', u'grecian', u'marigold', u"wrack'd", u'correct',
u'red', u'monster', u'belied', u'horse', u'free', u'mourning', u'pleasant',
u'cut', u'reason', u'base', u'rebel', u"t'", u'thrust', u'mistress', u'weed',
u'knit', u"feel'st", u'nightly', u'service', u'goest', u'misuse', u'could',
u'attainted', u'contented', u'honest', u'thing', u'place',
u'recompense', u'tempting', u"character'd", u'hence', u'sufferance', u'think',
u'first', u'blind', u'seeming', u'feel', u'pitied', u"gather'd", u'number',
u'rank', u'yourself', u"fil'd", u'done', u'chide', u'directly', u'blank',
u'sober', u'affords', u'moan', u'given', u'long', u"wand'ring", u'exchequer',
u'usurer', u'twenty', u'least', u'their', u'master', u'saint', u'bounty',
u'woe', u'bitter', u'friend', u'beard', u'hue', u'imperfect', u'that',
u'tongue', u'sweet', u'adonis', u'wisdom', u'woo', u'annoy', u'helen',
u'mayest', u'herself', u'than', u'begins', u'king', u'aught', u'coward',
u'folly', u'richer', u'bed', u'youth', u'matter', u'guilt', u'sens', u'were',
u'oath', u'threefold', u'and', u'accusing', u'fashion', u'few', u'slay',
u'well', u'correction', u'modern', u'argument', u'sad', u'tender', u'out',
u'alike', u'have', u'anger', u'churl', u'seem', u'sky', u'any', u'sensual',
u'issue', u'groan', u'governs', u'amends', u'note', u'lip', u'take', u'which',
u'resembling', u'lily', u'play', u'towards', u'shade', u'maiden', u'shall',
u'tomb', u'knew', u'me', u"mask'd", u'most', u'mouth', u'but', u'nothing',
u'why', u'shalt', u'proud', u'cover', u'disease', u'wing', u"dimm'd", u'sun',
u'justify', u'painting', u'sum', u"pow'rs", u'shop', u'affair', u'gold',
u'wailing', u'queen', u'cheap', u'merit', u'bring', u'bright', u'session',
u'earth', u'bail', u'gilded', u'slow', u'shouldst', u'knowledge', u'spite',
u'philomel', u'treasure', u'cloak', u'cupid', u'grace', u'being', u'only',
u'going', u'black', u'beauteous', u'consent', u'stain', u'forfeit', u'do',
u'hit', u'forsworn', u'distance', u"'tis", u'rock', u'watch', u'truly',
u'beam', u'remedy', u'breast', u'report', u'bird', u'distraction',
u'closure', u'bar', u'glory', u'alteration', u'method', u'dearest',
u'though', u'contain', u'kill', u'where', u'require', u'husband', u'widow',
u'penance', u'fair', u'jade', u'orphan', u'grey', u"pierc'd", u'depends',
u'defense', u'dumb', u'are', u'sea', u'corrupt', u'sport', u'outward',
u'best', u'subject', u'politic', u'forlorn', u'away', u'heavenly',
u'ornament', u'yet', u'favor', u'written', u'complexion', u'sable', u'scorn',
u'untainted', u'preserve', u'never', u'nature', u'joy', u'sorrow',
u'lover', u'ignorance', u'religious', u'weary', u'devour', u'diest',
u'precious', u'come', u'perfection', u'league', u'goddess', u'accident',
u'instant', u'disdain', u'thou', u'ill', u'equal', u'drug', u'admit',
u'present', u'lo', u"seal'd", u'bond', u'comes', u'comment', u'madness',
u"sav'd", u'majesty', u'drunk', u'wall', u'had', u"perjur'd", u'dispatch',
u'hast', u'slain', u'simply', u'flourish', u"ev'ry", u'speak', u'worthless',
u'devil', u"e'er", u'dun', u'addition', u'been', u'mark', u'whom', u'much',
u'ah', u'lovely', u'thrice', u'rather', u"'twixt", u'painted', u'thousand',
u'lion', u'wish', u'tiger', u'lift', u'dote', u'child', u'last', u'doth',
u'former', u'those', u'gracious', u'myself', u'gentle', u'these', u'sauce',
u'straight', u'lovest', u'appearance', u'single', u'air', u'lesser', u'cast',
u'while', u'situation', u'voice', u'fool', u'kindness', u'pyramid', u'almost',
u'is', u'it', u'sleeping', u'confound', u'shame', u'to-morrow', u'frantic',
u'in', u'commanded', u'bounteous', u'if', u'ransom', u'memorial', u'hound',
u'because', u'alien', u'perhaps', u'make', u'cross', u'same', u'discourse',
u'strange', u"th'", u'monarch', u"suppos'd", u'used', u'blest', u'see',
u'sickness', u'flesh', u'defy', u'upon', u'evil', u'hand', u'delight',
u'flown', u'purpose', u'supposing', u'fierce', u'judgment', u'longing',
u'scarcely', u'task', u'off', u'blood', u'cheek', u'itself',
u'loathsome', u'morrow', u'cheer', u'oft', u'knight', u'left',
u'summer', u'kiss', u'just', u'wasteful', u'yea', u'rest', u'foot', u'cease',
u'farther', u'depart', u'plight', u'speed', u'prince', u'unto', u'adding',
u'death', u'legion', u'rose', u'point', u'character', u'except', u'day',
u'verse', u'prison', u'hap', u'mournful', u'slave', u'raven', u'kingdom',
u'march', u'frown', u'freedom', u'testy', u'bid', u'advocate', u'mow',
u'dark', u'traffic', u'know', u'unseen', u'dearly', u'press', u'salve',
u'lady', u'woeful', u'dare', u'nay', u'fortune', u'gift', u'blunt', u'strife',
u'oblivion', u'night', u'tower', u'foolish', u'page', u'lends', u'antique',
u'canst', u'right', u'old', u'spring', u'creation', u'crown', u"o'erpress'd",
u'dead', u'hush', u'born', u'meditation', u'usher', u'sight', u'dear',
u'candle', u'pale', u'humor', u'for', u'antiquity', u'purple', u'rehearse',
u'balmy', u'moon', u"'fore", u'foe', u'confounds', u'passion', u"o'ertake",
u'lark', u"unlook'd", u'knife', u"possess'd", u'varying', u'who', u'run',
u'power', u'burn', u'aloft', u'paid', u'worthy', u'instinct', u'from', u'by',
u'shine', u'faith', u'about', u'works', u'rare', u'variation', u"flow'r",
u'coral', u'haply', u'o', u'sake', u'despair', u'wolf', u'stand', u'act',
u'hatred', u'luck', u'nerve', u'reckoning', u'own', u'presence', u'civil',
u'into', u'son', u'down', u'preposterously', u'pitying', u'lively',
u'strangely', u'pearl', u'there', u'question', u'sovereign', u'fast',
u'virgin', u'gaze', u'way', u'house', u'forward', u'hem', u'translate',
u'was', u'war', u'happy', u'function', u'head', u"slander'd", u'form',
u'believe', u'becoming', u'frost', u'forgetful', u'vowing', u'back',
u'heinous', u'suffers', u'hear', u'authority', u'might', u'survive',
u'happier', u'with', u'eat', u'bud', u'count', u'absent', u'immured',
u'made', u'wise', u'evident', u'thanks', u"for't", u'up', u'us', u'until',
u'crystal', u'more', u'thorn', u'gone', u'palate', u'fury', u'certain',
u'cheeks', u'deep', u'general', u'blot', u'as', u'sometime', u'goodness',
u'ink', u'ay', u'curl', u'face', u"borrow'd", u"cancell'd", u'sullen',
u'riot', u'dying', u'no', u'peace', u'when', u"look'd", u'field', u'book',
u'witness', u'sick', u'confine', u'abysm', u'poor', u'executor',
u'intend', u'phoenix', u'treason', u"profan'd", u'stay', u'chance',
u'censure', u'leaf', u'sequent', u'land', u'to-day', u'actor', u'vice',
u'blushing', u'vow', u'together', u'indirectly', u'profit', u'cheater',
u'mourner', u'receive'])
